"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 15:04:00.579950
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cnr', sa.String(length=32), nullable=True),
    sa.Column('case_numbers', sa.JSON(), nullable=False),
    sa.Column('court', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('fir_number', sa.String(length=50), nullable=True),
    sa.Column('police_station', sa.String(length=200), nullable=True),
    sa.Column('fir_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('status_confidence', sa.Float(), nullable=False),
    sa.Column('offence_date', sa.Date(), nullable=True),
    sa.Column('fir_date', sa.Date(), nullable=True),
    sa.Column('first_remand_date', sa.Date(), nullable=True),
    sa.Column('charge_sheet_date', sa.Date(), nullable=True),
    sa.Column('default_bail_application_date', sa.Date(), nullable=True),
    sa.Column('bail_granted_date', sa.Date(), nullable=True),
    sa.Column('conviction_date', sa.Date(), nullable=True),
    sa.Column('acquittal_date', sa.Date(), nullable=True),
    sa.Column('facts_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_cnr'), ['cnr'], unique=False)

    op.create_table('legal_verifications',
    sa.Column('record_key', sa.String(length=80), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=200), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('jail', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('charges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('act', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('modifier', sa.String(length=40), nullable=True),
    sa.Column('offence_date', sa.Date(), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('dropped_on', sa.Date(), nullable=True),
    sa.Column('aggravated', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hearings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('delay_attribution', sa.String(length=20), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('attribution_method', sa.String(length=40), nullable=True),
    sa.Column('reviewer_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('name_variants', sa.JSON(), nullable=False),
    sa.Column('relative_name_variants', sa.JSON(), nullable=False),
    sa.Column('relation', sa.String(length=8), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('dob_uncertainty_years', sa.Float(), nullable=True),
    sa.Column('age_at_offence', sa.Integer(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=False),
    sa.Column('identifiers', sa.JSON(), nullable=False),
    sa.Column('is_juvenile_at_offence', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_national', sa.Boolean(), nullable=False),
    sa.Column('vulnerability', sa.JSON(), nullable=False),
    sa.Column('jail', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('assigned_lawyer_id', sa.String(length=32), nullable=True),
    sa.Column('merged_into_id', sa.String(length=32), nullable=True),
    sa.Column('synthetic_truth_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_id', name='uq_review_kind_ref')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=32), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('channel_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_person_id'), ['person_id'], unique=False)

    op.create_table('case_persons',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'person_id')
    )
    op.create_table('convictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('offence', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custody_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('jail', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defense_insights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=4), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('next_steps', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('legal_basis', sa.JSON(), nullable=False),
    sa.Column('judgments', sa.JSON(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'case_id', 'code', name='uq_insight')
    )
    with op.batch_alter_table('defense_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defense_insights_person_id'), ['person_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('doc_type_confidence', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('scripts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('grounding', sa.JSON(), nullable=False),
    sa.Column('verifier_report', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=False),
    sa.Column('legal_data_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('eligible_from_date', sa.Date(), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_results_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_results_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_results_status'), ['status'], unique=False)

    op.create_table('merge_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kept_person_id', sa.String(length=32), nullable=False),
    sa.Column('merged_person_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('performed_by', sa.String(length=32), nullable=True),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kept_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['merged_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('span_text', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('corrected_value', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_runs')
    op.drop_table('extracted_facts')
    op.drop_table('merge_events')
    with op.batch_alter_table('eligibility_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_results_status'))
        batch_op.drop_index(batch_op.f('ix_eligibility_results_person_id'))
        batch_op.drop_index(batch_op.f('ix_eligibility_results_is_current'))

    op.drop_table('eligibility_results')
    op.drop_table('drafts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))

    op.drop_table('documents')
    with op.batch_alter_table('defense_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defense_insights_person_id'))

    op.drop_table('defense_insights')
    op.drop_table('custody_events')
    op.drop_table('convictions')
    op.drop_table('case_persons')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_person_id'))

    op.drop_table('alerts')
    op.drop_table('review_items')
    op.drop_table('persons')
    op.drop_table('hearings')
    op.drop_table('charges')
    op.drop_table('users')
    op.drop_table('legal_verifications')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_cnr'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
